<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGaTHRYv\undpaul_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGaTHRYv/undpaul_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerGaTHRYv.legacy');

    return;
}

if (!\class_exists(undpaul_KernelDevContainer::class, false)) {
    \class_alias(\ContainerGaTHRYv\undpaul_KernelDevContainer::class, undpaul_KernelDevContainer::class, false);
}

return new \ContainerGaTHRYv\undpaul_KernelDevContainer([
    'container.build_hash' => 'GaTHRYv',
    'container.build_id' => '38252096',
    'container.build_time' => 1726473065,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGaTHRYv');
