<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NRrHWWlService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.nRrHWWl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nRrHWWl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'definition' => ['privates', '.errored.SdOoNXF', NULL, 'Cannot determine controller argument for "undpaul\\toggl2redmine\\Command\\TimeEntrySync::setDefinition()": the $definition argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Console\\Input\\InputDefinition|array".'],
        ], [
            'definition' => '?',
        ]);
    }
}
