<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_WcIy8u3_DateTimeService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.wcIy8u3.DateTime' shared service.
     *
     * @return \DateTime
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wcIy8u3": it references class "DateTime" but no such service exists.');
    }
}
