<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_SdOoNXFService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored.SdOoNXF' shared service.
     *
     * @return \Symfony\Component\Console\Input\InputDefinition|array
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "undpaul\\toggl2redmine\\Command\\TimeEntrySync::setDefinition()": the $definition argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Console\\Input\\InputDefinition|array".');
    }
}
