<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_6dmKh5z_ClosurearrayService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.6dmKh5z.Closure|array' shared service.
     *
     * @return \Closure|array
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6dmKh5z": it has type "Closure|array" but this class was not found.');
    }
}
