<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'undpaul\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'undpaul\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::processTimeEntries' => ['privates', '.service_locator.FMaSm1H.undpaul\\toggl2redmine\\Command\\TimeEntrySync::processTimeEntries()', 'getTimeEntrySyncprocessTimeEntriesService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::syncTimeEntry' => ['privates', '.service_locator.77SdJka.undpaul\\toggl2redmine\\Command\\TimeEntrySync::syncTimeEntry()', 'getTimeEntrySyncsyncTimeEntryService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::getTimeEntries' => ['privates', '.service_locator.wcIy8u3.undpaul\\toggl2redmine\\Command\\TimeEntrySync::getTimeEntries()', 'getTimeEntrySyncgetTimeEntriesService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::setHelperSet' => ['privates', '.service_locator.m_.70vw.undpaul\\toggl2redmine\\Command\\TimeEntrySync::setHelperSet()', 'getTimeEntrySyncsetHelperSetService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::run' => ['privates', '.service_locator.8zGno_O.undpaul\\toggl2redmine\\Command\\TimeEntrySync::run()', 'getTimeEntrySyncrunService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::complete' => ['privates', '.service_locator.qYl6tIR.undpaul\\toggl2redmine\\Command\\TimeEntrySync::complete()', 'getTimeEntrySynccompleteService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::setDefinition' => ['privates', '.service_locator.nRrHWWl', 'get_ServiceLocator_NRrHWWlService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::addArgument' => ['privates', '.service_locator.6dmKh5z.undpaul\\toggl2redmine\\Command\\TimeEntrySync::addArgument()', 'getTimeEntrySyncaddArgumentService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::addOption' => ['privates', '.service_locator.6dmKh5z.undpaul\\toggl2redmine\\Command\\TimeEntrySync::addOption()', 'getTimeEntrySyncaddOptionService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:processTimeEntries' => ['privates', '.service_locator.FMaSm1H.undpaul\\toggl2redmine\\Command\\TimeEntrySync::processTimeEntries()', 'getTimeEntrySyncprocessTimeEntriesService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:syncTimeEntry' => ['privates', '.service_locator.77SdJka.undpaul\\toggl2redmine\\Command\\TimeEntrySync::syncTimeEntry()', 'getTimeEntrySyncsyncTimeEntryService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:getTimeEntries' => ['privates', '.service_locator.wcIy8u3.undpaul\\toggl2redmine\\Command\\TimeEntrySync::getTimeEntries()', 'getTimeEntrySyncgetTimeEntriesService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:setHelperSet' => ['privates', '.service_locator.m_.70vw.undpaul\\toggl2redmine\\Command\\TimeEntrySync::setHelperSet()', 'getTimeEntrySyncsetHelperSetService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:run' => ['privates', '.service_locator.8zGno_O.undpaul\\toggl2redmine\\Command\\TimeEntrySync::run()', 'getTimeEntrySyncrunService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:complete' => ['privates', '.service_locator.qYl6tIR.undpaul\\toggl2redmine\\Command\\TimeEntrySync::complete()', 'getTimeEntrySynccompleteService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:setDefinition' => ['privates', '.service_locator.nRrHWWl', 'get_ServiceLocator_NRrHWWlService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:addArgument' => ['privates', '.service_locator.6dmKh5z.undpaul\\toggl2redmine\\Command\\TimeEntrySync::addArgument()', 'getTimeEntrySyncaddArgumentService', true],
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:addOption' => ['privates', '.service_locator.6dmKh5z.undpaul\\toggl2redmine\\Command\\TimeEntrySync::addOption()', 'getTimeEntrySyncaddOptionService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'undpaul\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'undpaul\\Kernel::loadRoutes' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::processTimeEntries' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::syncTimeEntry' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::getTimeEntries' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::setHelperSet' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::run' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::complete' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::setDefinition' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::addArgument' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync::addOption' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:processTimeEntries' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:syncTimeEntry' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:getTimeEntries' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:setHelperSet' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:run' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:complete' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:setDefinition' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:addArgument' => '?',
            'undpaul\\toggl2redmine\\Command\\TimeEntrySync:addOption' => '?',
        ]));
    }
}
