<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompletionInputService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.qYl6tIR.Symfony\Component\Console\Completion\CompletionInput' shared service.
     *
     * @return \Symfony\Component\Console\Completion\CompletionInput
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qYl6tIR": it references class "Symfony\\Component\\Console\\Completion\\CompletionInput" but no such service exists.');
    }
}
