<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelperSetService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.m_.70vw.Symfony\Component\Console\Helper\HelperSet' shared service.
     *
     * @return \Symfony\Component\Console\Helper\HelperSet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m_.70vw": it references class "Symfony\\Component\\Console\\Helper\\HelperSet" but no such service exists.');
    }
}
