<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInputInterfaceService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.8zGno_O.Symfony\Component\Console\Input\InputInterface' shared service.
     *
     * @return \Symfony\Component\Console\Input\InputInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8zGno_O": it references interface "Symfony\\Component\\Console\\Input\\InputInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
