<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntryCollectionService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.FMaSm1H.undpaul\toggl2redmine\TimeEntryCollection' shared service.
     *
     * @return \undpaul\toggl2redmine\TimeEntryCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FMaSm1H": it references class "undpaul\\toggl2redmine\\TimeEntryCollection" but no such service exists.');
    }
}
