<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySyncrunService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.8zGno_O.undpaul\toggl2redmine\Command\TimeEntrySync::run()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8zGno_O.undpaul\\toggl2redmine\\Command\\TimeEntrySync::run()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'input' => ['privates', '.errored..service_locator.8zGno_O.Symfony\\Component\\Console\\Input\\InputInterface', NULL, 'Cannot autowire service ".service_locator.8zGno_O": it references interface "Symfony\\Component\\Console\\Input\\InputInterface" but no such service exists. Did you create a class that implements this interface?'],
            'output' => ['privates', '.errored..service_locator.8zGno_O.Symfony\\Component\\Console\\Output\\OutputInterface', NULL, 'Cannot autowire service ".service_locator.8zGno_O": it references interface "Symfony\\Component\\Console\\Output\\OutputInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'input' => 'Symfony\\Component\\Console\\Input\\InputInterface',
            'output' => 'Symfony\\Component\\Console\\Output\\OutputInterface',
        ]))->withContext('undpaul\\toggl2redmine\\Command\\TimeEntrySync::run()', $container);
    }
}
