<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySyncgetTimeEntriesService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.wcIy8u3.undpaul\toggl2redmine\Command\TimeEntrySync::getTimeEntries()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wcIy8u3.undpaul\\toggl2redmine\\Command\\TimeEntrySync::getTimeEntries()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'from' => ['privates', '.errored..service_locator.wcIy8u3.DateTime', NULL, 'Cannot autowire service ".service_locator.wcIy8u3": it references class "DateTime" but no such service exists.'],
            'to' => ['privates', '.errored..service_locator.wcIy8u3.DateTime', NULL, 'Cannot autowire service ".service_locator.wcIy8u3": it references class "DateTime" but no such service exists.'],
        ], [
            'from' => 'DateTime',
            'to' => 'DateTime',
        ]))->withContext('undpaul\\toggl2redmine\\Command\\TimeEntrySync::getTimeEntries()', $container);
    }
}
