<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySyncService extends undpaul_KernelDevContainer
{
    /*
     * Gets the public 'undpaul\toggl2redmine\Command\TimeEntrySync' shared autowired service.
     *
     * @return \undpaul\toggl2redmine\Command\TimeEntrySync
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['undpaul\\toggl2redmine\\Command\\TimeEntrySync'] = $instance = new \undpaul\toggl2redmine\Command\TimeEntrySync();

        $instance->setName('time-entry-sync');
        $instance->setDescription('Synchronize time entry records between toggl and redmine.');

        return $instance;
    }
}
