<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySyncprocessTimeEntriesService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.FMaSm1H.undpaul\toggl2redmine\Command\TimeEntrySync::processTimeEntries()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FMaSm1H.undpaul\\toggl2redmine\\Command\\TimeEntrySync::processTimeEntries()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'collection' => ['privates', '.errored..service_locator.FMaSm1H.undpaul\\toggl2redmine\\TimeEntryCollection', NULL, 'Cannot autowire service ".service_locator.FMaSm1H": it references class "undpaul\\toggl2redmine\\TimeEntryCollection" but no such service exists.'],
        ], [
            'collection' => 'undpaul\\toggl2redmine\\TimeEntryCollection',
        ]))->withContext('undpaul\\toggl2redmine\\Command\\TimeEntrySync::processTimeEntries()', $container);
    }
}
