<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySyncaddOptionService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.6dmKh5z.undpaul\toggl2redmine\Command\TimeEntrySync::addOption()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6dmKh5z.undpaul\\toggl2redmine\\Command\\TimeEntrySync::addOption()'] = ($container->privates['.service_locator.6dmKh5z'] ?? $container->load('get_ServiceLocator_6dmKh5zService'))->withContext('undpaul\\toggl2redmine\\Command\\TimeEntrySync::addOption()', $container);
    }
}
