<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntryService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.77SdJka.undpaul\toggl2redmine\TimeEntry' shared service.
     *
     * @return \undpaul\toggl2redmine\TimeEntry
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.77SdJka": it references class "undpaul\\toggl2redmine\\TimeEntry" but no such service exists.');
    }
}
