<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySyncsetHelperSetService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.m_.70vw.undpaul\toggl2redmine\Command\TimeEntrySync::setHelperSet()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m_.70vw.undpaul\\toggl2redmine\\Command\\TimeEntrySync::setHelperSet()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'helperSet' => ['privates', '.errored..service_locator.m_.70vw.Symfony\\Component\\Console\\Helper\\HelperSet', NULL, 'Cannot autowire service ".service_locator.m_.70vw": it references class "Symfony\\Component\\Console\\Helper\\HelperSet" but no such service exists.'],
        ], [
            'helperSet' => 'Symfony\\Component\\Console\\Helper\\HelperSet',
        ]))->withContext('undpaul\\toggl2redmine\\Command\\TimeEntrySync::setHelperSet()', $container);
    }
}
