<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySynccompleteService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.qYl6tIR.undpaul\toggl2redmine\Command\TimeEntrySync::complete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qYl6tIR.undpaul\\toggl2redmine\\Command\\TimeEntrySync::complete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'input' => ['privates', '.errored..service_locator.qYl6tIR.Symfony\\Component\\Console\\Completion\\CompletionInput', NULL, 'Cannot autowire service ".service_locator.qYl6tIR": it references class "Symfony\\Component\\Console\\Completion\\CompletionInput" but no such service exists.'],
            'suggestions' => ['privates', '.errored..service_locator.qYl6tIR.Symfony\\Component\\Console\\Completion\\CompletionSuggestions', NULL, 'Cannot autowire service ".service_locator.qYl6tIR": it references class "Symfony\\Component\\Console\\Completion\\CompletionSuggestions" but no such service exists.'],
        ], [
            'input' => 'Symfony\\Component\\Console\\Completion\\CompletionInput',
            'suggestions' => 'Symfony\\Component\\Console\\Completion\\CompletionSuggestions',
        ]))->withContext('undpaul\\toggl2redmine\\Command\\TimeEntrySync::complete()', $container);
    }
}
