<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySyncsyncTimeEntryService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.77SdJka.undpaul\toggl2redmine\Command\TimeEntrySync::syncTimeEntry()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.77SdJka.undpaul\\toggl2redmine\\Command\\TimeEntrySync::syncTimeEntry()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entry' => ['privates', '.errored..service_locator.77SdJka.undpaul\\toggl2redmine\\TimeEntry', NULL, 'Cannot autowire service ".service_locator.77SdJka": it references class "undpaul\\toggl2redmine\\TimeEntry" but no such service exists.'],
        ], [
            'entry' => 'undpaul\\toggl2redmine\\TimeEntry',
        ]))->withContext('undpaul\\toggl2redmine\\Command\\TimeEntrySync::syncTimeEntry()', $container);
    }
}
