<?php

namespace ContainerGaTHRYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeEntrySync_LazyService extends undpaul_KernelDevContainer
{
    /*
     * Gets the private '.undpaul\toggl2redmine\Command\TimeEntrySync.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.undpaul\\toggl2redmine\\Command\\TimeEntrySync.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('time-entry-sync', [], 'Synchronize time entry records between toggl and redmine.', false, #[\Closure(name: 'undpaul\\toggl2redmine\\Command\\TimeEntrySync')] fn (): \undpaul\toggl2redmine\Command\TimeEntrySync => ($container->services['undpaul\\toggl2redmine\\Command\\TimeEntrySync'] ?? $container->load('getTimeEntrySyncService')));
    }
}
